version: '3'

services:
  poll:
    build:
      context: ./poll
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  db:
    image: postgres
    environment:
      - POSTGRES_DB=foobar
      - POSTGRES_USER=foobar
      - POSTGRES_PASSWORD=barfoo
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"

    networks:
      - result-tier
      - back-tier

  redis:
    image: "redis:alpine"
    ports: ["6379"]
    networks:
      - poll-tier
      - back-tier

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=foobar
      - POSTGRES_USER=foobar
      - POSTGRES_PASSWORD=barfoo
  

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: